### PR TITLE
[WIP] Monorepo structure

### PR DESCRIPTION
**Pull request by apolloFER**
This creates a Monorepo structure. Moves Mapier API to Mapier repository.
Allows us to build a single image for both Mapier and Mapier-API (only a single deploy needed for both in `helm-configs`.

Docker-compose has been updated to support the new structure.

WIP since it still needs updated README, instructions and similar stuff.

Tested out everything with Docker compose and it works.

### CODE REVIEW

**Comment by jdaudier** [comment]
@ruebel I'd be happy to help review the new feature. Excited to check it out!

**Comment by rtnpro** [comment]
@ruebel @jdaudier Are the mapier big refactor changes in yet? Can we start working on this again?

**Comment by jdaudier** [comment]
@rtnpro I think we need a few more days. We're aiming to merge it by next Fri. Will that work for you?

**Comment by rtnpro** [comment]
Yes, we'll wait for you to complete the refactor @jdaudier 👍 Ping us once your changes are in.

**Comment by iterion** [comment]
Closing this now that the new features have been merged and the new PR started: #8

**Pull request closed without merging**
